ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - JAVASCRIPT_PRETTIER
  - YAML_PRETTIER
  - SPELL_VALE
  - DOCKERFILE_HADOLINT
  - SECRET_GITLEAKS

FLAVOR_SUGGESTIONS: false
SECURITY_SUGGESTIONS: false

ADDITIONAL_EXCLUDED_DIRECTORIES:
  - .bundle
  - .jekyll-cache
  - .opencode
  - megalinter-reports
  - _site
  - node_modules
  - public
  - resources
  - vendor

MARKDOWN_MARKDOWNLINT_FILE_EXTENSIONS:
  - .md

JAVASCRIPT_PRETTIER_FILE_EXTENSIONS:
  - .js
  - .json
  - .md

YAML_PRETTIER_FILE_EXTENSIONS:
  - .yml
  - .yaml

SPELL_VALE_FILE_EXTENSIONS:
  - .md

DOCKERFILE_HADOLINT_FILE_NAMES_REGEX:
  - Containerfile
  - (.*\.)?Dockerfile
