repos:
  - repo: https://github.com/oxsecurity/megalinter
    rev: ef3e84b8b836d76db562d0f3ed7da61e8fd538bc # frozen: v9.6.0
    hooks:
      - id: megalinter-incremental
        entry: bash .github/scripts/mega-linter-runner
        args:
          - --containername
          - megalinter-incremental
          - --container-engine
          - podman
          - --remove-container
          - --nodockerpull
          - --fix
          - --filesonly
